const os = require('os');
const path = require('path');
const fs = require('fs');

/**
 * Root directory for all persistent Ultimatter configuration,
 * keys, and certificates (~/.config/ultimatter).
 * In test mode (NODE_ENV=test), an isolated temporary directory in /tmp is used
 * so tests never mutate or overwrite real user tokens or certificates.
 */
const CONFIG_DIR = process.env.NODE_ENV === 'test'
  ? path.join(os.tmpdir(), 'ultimatter-test-config')
  : path.join(os.homedir(), '.config', 'ultimatter');

// Ensure directory exists with restricted user-only permissions (0o700)
if (!fs.existsSync(CONFIG_DIR)) {
  fs.mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
}

/** Path to the persistent cryptographic secrets JSON file */
const SECRETS_FILE = path.join(CONFIG_DIR, '.secret.json');

/**
 * Local Wi-Fi TLS Server Certificates:
 * - LOCAL_CERT_FILE (cert.pem): Server TLS Certificate generated by mkcert.
 * - LOCAL_KEY_FILE (key.pem): Server Private Key.
 * Note: The Root CA (rootCA.pem) is managed by mkcert in its CAROOT directory
 * and served via /api/ca.pem for mobile phone installation.
 */
const LOCAL_CERT_FILE = path.join(CONFIG_DIR, 'cert.pem');
const LOCAL_KEY_FILE = path.join(CONFIG_DIR, 'key.pem');

/**
 * Resolves the Let's Encrypt certificate and private key file paths
 * generated by Tailscale for a given MagicDNS hostname.
 * 
 * @param {string} dnsName - Tailscale MagicDNS domain (e.g. "ultramarine.cymric-dace.ts.net")
 * @returns {{ certFile: string, keyFile: string }}
 */
const getTailscaleCertFiles = (dnsName) => ({
  certFile: path.join(CONFIG_DIR, `${dnsName}.crt`),
  keyFile: path.join(CONFIG_DIR, `${dnsName}.key`)
});

/** Path to the persistent settings JSON file */
const SETTINGS_FILE = path.join(CONFIG_DIR, 'settings.json');

/**
 * Checks whether the mobile floating switcher bubble is enabled.
 * Defaults to false (clean native full-screen mode).
 * 
 * @returns {boolean}
 */
const getBubbleEnabled = () => {
  if (fs.existsSync(SETTINGS_FILE)) {
    try {
      const settings = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8'));
      if (typeof settings.mobileBubbleEnabled === 'boolean') {
        return settings.mobileBubbleEnabled;
      }
    } catch (e) {}
  }
  return false;
};

/**
 * Persists the mobile floating switcher bubble preference.
 * 
 * @param {boolean} enabled
 * @returns {boolean} New state
 */
const setBubbleEnabled = (enabled) => {
  let settings = {};
  if (fs.existsSync(SETTINGS_FILE)) {
    try {
      settings = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8'));
    } catch (e) {}
  }
  settings.mobileBubbleEnabled = Boolean(enabled);
  fs.writeFileSync(SETTINGS_FILE, JSON.stringify(settings, null, 2), { mode: 0o600 });
  return settings.mobileBubbleEnabled;
};

module.exports = {
  CONFIG_DIR,
  SECRETS_FILE,
  SETTINGS_FILE,
  LOCAL_CERT_FILE,
  LOCAL_KEY_FILE,
  getTailscaleCertFiles,
  getBubbleEnabled,
  setBubbleEnabled
};
