const os = require('os');
const path = require('path');
const fs = require('fs');

/**
 * Root directory for all persistent Ultimatter configuration,
 * keys, and certificates (~/.config/ultimatter).
 */
const CONFIG_DIR = path.join(os.homedir(), '.config', 'ultimatter');

// Ensure directory exists with restricted user-only permissions (0o700)
if (!fs.existsSync(CONFIG_DIR)) {
  fs.mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
}

/** Path to the persistent cryptographic secrets JSON file */
const SECRETS_FILE = path.join(CONFIG_DIR, '.secret.json');

/**
 * Local Wi-Fi TLS Server Certificates:
 * - LOCAL_CERT_FILE (cert.pem): Server TLS Certificate generated by mkcert.
 * - LOCAL_KEY_FILE (key.pem): Server Private Key.
 * Note: The Root CA (rootCA.pem) is managed by mkcert in its CAROOT directory
 * and served via /api/ca.pem for mobile phone installation.
 */
const LOCAL_CERT_FILE = path.join(CONFIG_DIR, 'cert.pem');
const LOCAL_KEY_FILE = path.join(CONFIG_DIR, 'key.pem');

/**
 * Resolves the Let's Encrypt certificate and private key file paths
 * generated by Tailscale for a given MagicDNS hostname.
 * 
 * @param {string} dnsName - Tailscale MagicDNS domain (e.g. "ultramarine.cymric-dace.ts.net")
 * @returns {{ certFile: string, keyFile: string }}
 */
const getTailscaleCertFiles = (dnsName) => ({
  certFile: path.join(CONFIG_DIR, `${dnsName}.crt`),
  keyFile: path.join(CONFIG_DIR, `${dnsName}.key`)
});

/** Path to the persistent settings JSON file */
const SETTINGS_FILE = path.join(CONFIG_DIR, 'settings.json');

module.exports = {
  CONFIG_DIR,
  SECRETS_FILE,
  SETTINGS_FILE,
  LOCAL_CERT_FILE,
  LOCAL_KEY_FILE,
  getTailscaleCertFiles
};
